/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    CommentEditor: typeof import('./src/components/CommentEditor.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CoreEditor: typeof import('./src/components/CoreEditor.vue')['default']
    Dialogs: typeof import('./src/components/Dialogs.vue')['default']
    DocumentList: typeof import('./src/components/DocumentList.vue')['default']
    ErrorPage: typeof import('./src/components/ErrorPage.vue')['default']
    FDialogs: typeof import('./src/components/FDialogs.vue')['default']
    FloatingComments: typeof import('./src/components/FloatingComments.vue')['default']
    FontSelect: typeof import('./src/components/FontSelect.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    LucideArrowBigLeft: typeof import('~icons/lucide/arrow-big-left')['default']
    LucideBadgeCheck: typeof import('~icons/lucide/badge-check')['default']
    LucideBuilding2: typeof import('~icons/lucide/building2')['default']
    LucideCheck: typeof import('~icons/lucide/check')['default']
    LucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    LucideEllipsis: typeof import('~icons/lucide/ellipsis')['default']
    LucideFileQuestionMark: typeof import('~icons/lucide/file-question-mark')['default']
    LucideFileText: typeof import('~icons/lucide/file-text')['default']
    LucideFolderClosed: typeof import('~icons/lucide/folder-closed')['default']
    LucideFolderPlus: typeof import('~icons/lucide/folder-plus')['default']
    LucideGlobe2: typeof import('~icons/lucide/globe2')['default']
    LucideHome: typeof import('~icons/lucide/home')['default']
    LucideMessageCircleCode: typeof import('~icons/lucide/message-circle-code')['default']
    LucideMessageCircleReply: typeof import('~icons/lucide/message-circle-reply')['default']
    LucideUser: typeof import('~icons/lucide/user')['default']
    LucideUsers: typeof import('~icons/lucide/users')['default']
    LucideX: typeof import('~icons/lucide/x')['default']
    ManageFont: typeof import('./src/components/ManageFont.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewVersionDialog: typeof import('./src/components/NewVersionDialog.vue')['default']
    NonCollabEditor: typeof import('./src/components/NonCollabEditor.vue')['default']
    NumberInput: typeof import('./src/components/controls/NumberInput.vue')['default']
    RemoveDialog: typeof import('./src/components/RemoveDialog.vue')['default']
    RoundedListView: typeof import('./src/components/RoundedListView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    SpacingDialog: typeof import('./src/components/SpacingDialog.vue')['default']
    TemplateDialog: typeof import('./src/components/TemplateDialog.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    ToC: typeof import('./src/components/ToC.vue')['default']
    UsersBar: typeof import('./src/components/UsersBar.vue')['default']
    VersionsSidebar: typeof import('./src/components/VersionsSidebar.vue')['default']
    WriterLogo: typeof import('./src/components/WriterLogo.vue')['default']
    WriterSettings: typeof import('./src/components/WriterSettings.vue')['default']
  }
}
